name:  'Hello Workflow'

on: 
  push:
        branches:
                - 'main'

        jobs:
            greet:
                  runs-on: 'ubuntu-latest'
                      steps:
                              - name: 'Say Hello'
                                      run: echo "Hello, MD! Welcome to GitHub Actions "

